name: 同步国内 Ollama & WebUI

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 拉取国内 Ollama
        run: docker pull docker.m.daocloud.io/ollama/ollama:latest

      - name: 打标签
        run: docker tag docker.m.daocloud.io/ollama/ollama:latest ghcr.io/${{ github.repository_owner }}/ollama:latest

      - name: 推送到私仓
        run: docker push ghcr.io/${{ github.repository_owner }}/ollama:latest

      - name: 拉取国内 Open WebUI
        run: docker pull docker.m.daocloud.io/open-webui/open-webui:main

      - name: 打标签
        run: docker tag docker.m.daocloud.io/open-webui/open-webui:main ghcr.io/${{ github.repository_owner }}/open-webui:main

      - name: 推送到私仓
        run: docker push ghcr.io/${{ github.repository_owner }}/open-webui:main
